name: Snapshot build

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install dependencies
      run: |
          yarn install

    - uses: rlespinasse/github-slug-action@master

    - name: setting nodejs
      uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: 'https://stg-gke-eu.voxeet.net/nexus/repository/npm-private-snapshot/'
        always-auth: true

    - name: build and publish
      run: |
          yarn publish
      env:
          NODE_AUTH_TOKEN: ${{ secrets.NEXUS_AUTH_TOKEN }}
